version: 0.2

env:
  variables:
    CI: "true"
    REPOSITORY_REGION: "eu-central-1"
    ENV: "dev"
    APP_NAME: "demo4"
    TERRAFORM_VERSION: "1.2.0-rc2"
    TERRAGRUNT_VERSION: "0.37.1"
    
phases:
  pre_build:
    commands:
      - aws configure list
      - curl -sSL "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip" -o terraform.zip
      - unzip terraform.zip -d /usr/local/bin && chmod +x /usr/local/bin/terraform
      - curl -sSL https://github.com/gruntwork-io/terragrunt/releases/download/v${TERRAGRUNT_VERSION}/terragrunt_linux_amd64 -o terragrunt
      - mv terragrunt /usr/local/bin/ && chmod +x /usr/local/bin/terragrunt
      - export REGISTRY_ID=`aws sts get-caller-identity --output text | awk '{print $1}'`
      - export REPO_NAME="${REGISTRY_ID}.dkr.ecr.${REPOSITORY_REGION}.amazonaws.com/${APP_NAME}-${ENV}"
      - pip install jq
      - echo "Getting existing tag"
      - export SERVICE_ARN=$(aws ecs list-services --cluster ${APP_NAME}-${ENV}-cluster | jq -r .serviceArns[])
      - export TASKDEF_ARN=$(aws ecs describe-services --cluster ${APP_NAME}-${ENV}-cluster --service ${SERVICE_ARN} | jq -r .services[].taskDefinition)
      - export EXISTING_TAG=$(aws ecs describe-task-definition --task-definition ${TASKDEF_ARN} | jq -r .taskDefinition.containerDefinitions[].image | tr ':' ' ' | awk '{print $2}')
      - echo "Current version is ${EXISTING_TAG}"
      
  build:
    commands:
      - echo "Build and push docker images"
      - cd "${CODEBUILD_SRC_DIR}/app"
      - export TAG="${CODEBUILD_RESOLVED_SOURCE_VERSION}-${ENV}"
      - echo "$AWS_PROFILE"
      - echo "Building version ${TAG}"
      - make build
      - cd "$CODEBUILD_SRC_DIR"
      # - RUNNING_TASKS=$(aws ecs list-tasks --cluster ${APP_NAME}-${ENV}-cluster | jq -r .taskArns[] | tr '/' ' ' | awk '{print$3}')
      # - for task in $RUNNING_TASKS; do aws ecs stop-task --cluster ${APP_NAME}-${ENV}-cluster --task $task; done
      - terragrunt plan --terragrunt-working-dir environment/dev/ecs/ -var="image_tag=${TAG}" -no-color -input=false -out plan.out
      - terragrunt apply --terragrunt-working-dir environment/dev/ecs/ -auto-approve -no-color -input=false plan.out
      - RUNNING_TASKS=$(aws ecs list-tasks --cluster ${APP_NAME}-${ENV}-cluster | jq -r .taskArns[] | tr '/' ' ' | awk '{print$3}')
      - for task in $RUNNING_TASKS; do aws ecs stop-task --cluster demo3-dev-cluster --task $task; done
      - aws ecs update-service --force-new-deployment --service ${APP_NAME}-${ENV}-service --cluster ${APP_NAME}-${ENV}-cluster


  post_build:
    commands:
      - | 
        if [ $CODEBUILD_BUILD_SUCCEEDING != 0 ]; then
          NEWTAG=''
          while [ "${NEWTAG}" != "${TAG}" ]; 
          do 
            NEW_ARN=$(aws ecs list-services --cluster ${APP_NAME}-${ENV}-cluster | jq -r .serviceArns[])
            NEW_TASKDEF=$(aws ecs describe-services --cluster ${APP_NAME}-${ENV}-cluster --service ${NEW_ARN} | jq -r .services[].taskDefinition)
            NEWTAG=$(aws ecs describe-task-definition --task-definition ${NEW_TASKDEF} | jq -r .taskDefinition.containerDefinitions[].image | tr ':' ' ' | awk '{print $2}')
            echo "Waiting until new image started... Tag: ${TAG} New tag: ${NEWTAG}"
            if [ "${NEWTAG}" != ${TAG} ]; then
              sleep 10
            fi
          done
        else
          echo "Build failed"
        fi
      - echo "Cluster has been deployed"
